# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

ZSH_THEME="avit"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

plugins=(docker git httpie)

# User configuration

source $ZSH/oh-my-zsh.sh
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR='vi'
DEFAULT_USER='mephisto'
export PGUSER=postgres

# the following trick forces zsh to rely on ~/.dircolors, if present
# to tweak colors, generate this file with `dircolors --print-database`, and adjust
unset LS_COLORS

PATH=~/bin:$PATH

bindkey -v
export KEYTIMEOUT=1
alias no="ls"
alias p=r
alias mrs="./manage.py runserver"
alias doco="docker-compose"
alias yolo="git pull --rebase && git push"
alias killem="ps aux |grep runserver |grep -v grep |awk '{print \$2}' |xargs kill"
alias vi="nvim"
alias runtags="ctags -R --languages=Python ."
alias watchhtml="ag -l --html|entr touch manage.py &"

# oh noes, ubuntu doesn't have pbcopy. if only we had some alternative
alias pbcopy="xclip -i -selection clipboard"
alias pbpaste="xclip -i -selection clipboard -o"

# just a temporary hack because i can't be arsed to set up ES properly :)
alias esrun='/usr/share/elasticsearch/bin/elasticsearch &'

AUTO_CD="true"

export NVM_DIR="/home/mephisto/dev/asics-gtm/asics/static/frontend/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

cowsay -e "^^" `fortune`

export PYTHONDONTWRITEBYTECODE=1

# pyenv stuff
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - 2>/dev/null)"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
